@extends('layouts.app')
@section('title',$isEdit?'Editar agenda preventiva':'Adicionar agenda preventiva')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">@endpush
@section('content')
<div class="mb-4"><h1 class="page-title">Agendamento de Manutenções Preventivas</h1><p class="page-description mb-0">{{ $isEdit?'Atualize os dados do agendamento.':'Cadastre a primeira agenda preventiva do equipamento.' }}</p></div>
<form method="POST" action="{{ $isEdit?route('agenda.update',$agenda->id):route('agenda.store') }}">@csrf @if($isEdit)@method('PUT')@endif
<div class="card content-card"><div class="card-header"><h5>Dados do agendamento</h5></div><div class="card-body p-4">
@if($errors->any())<div class="alert alert-danger"><strong>Verifique os campos informados.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
<div class="col-12"><label for="ativos_id" class="form-label">Ativo / Equipamento</label><select id="ativos_id" name="ativos_id" class="form-select" required><option value="">Selecione um ativo</option>@foreach($ativos as $item)@php($localUnidade=($item->local?->titulo?:'Local não informado').' - '.($item->local?->unidade?->titulo?:'Unidade não informada'))<option value="{{ $item->id }}" data-local-id="{{ $item->locais_id }}" data-local-unidade="{{ $localUnidade }}" @selected((string)old('ativos_id',$agenda->ativos_id)===(string)$item->id)>{{ $item->titulo?:"Ativo #{$item->id}" }} ({{ $item->codigo?:'sem código' }}) - {{ $localUnidade }}</option>@endforeach</select></div>
<div class="col-12"><label for="local_unidade" class="form-label">Local - Unidade</label><input id="local_unidade" class="form-control" disabled><input id="locais_id" name="locais_id" type="hidden" value="{{ old('locais_id',$agenda->locais_id) }}"></div>
<div class="col-md-4"><label for="ultima_agenda" class="form-label">{{ $isEdit?'Última Agenda':'Primeira Agenda' }}</label><input id="ultima_agenda" name="ultima_agenda" type="date" class="form-control" value="{{ old('ultima_agenda',$agenda->ultima_agenda?->format('Y-m-d')) }}"></div>
<div class="col-md-4"><label for="periodicidade" class="form-label">Periodicidade (nº dias)</label><input id="periodicidade" name="periodicidade" type="number" min="0" class="form-control" value="{{ old('periodicidade',$agenda->periodicidade) }}"></div>
<div class="col-md-4"><label for="proxima_agenda" class="form-label">Próxima Agenda</label><input id="proxima_agenda" name="proxima_agenda" type="date" class="form-control" value="{{ old('proxima_agenda',$agenda->proxima_agenda?->format('Y-m-d')) }}"></div>
<div class="col-md-6"><label for="orcamento" class="form-label">Orçamento (nº dias antes da data)</label><input id="orcamento" name="orcamento" type="number" min="0" class="form-control" value="{{ old('orcamento',$agenda->orcamento) }}"></div>
<div class="col-md-6"><label for="proximo_orcamento" class="form-label">Próximo Orçamento</label><input id="proximo_orcamento" name="proximo_orcamento" type="date" class="form-control" value="{{ old('proximo_orcamento',$agenda->proximo_orcamento?->format('Y-m-d')) }}"></div>
<div class="col-12"><label for="obs" class="form-label">Observações</label><textarea id="obs" name="obs" maxlength="250" rows="4" class="form-control">{{ old('obs',$agenda->obs) }}</textarea></div>
<div class="col-12"><input type="hidden" name="ativo" value="0"><div class="form-check form-switch"><input id="ativo" name="ativo" value="1" type="checkbox" class="form-check-input" @checked((bool)old('ativo',$agenda->ativo))><label class="form-check-label" for="ativo">Status ativado</label></div></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('agenda.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>{{ $isEdit?'Salvar':'Cadastrar' }}</button></div>
</div></div></form>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script>
$(function(){const ativo=$('#ativos_id').select2({theme:'bootstrap-5',width:'100%',placeholder:'Selecione ou pesquise um ativo',language:{noResults:()=> 'Nenhum ativo encontrado'}});const date=(value,days)=>{if(!value||!Number.isInteger(days))return '';const d=new Date(value+'T00:00:00');d.setDate(d.getDate()+days);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};const local=()=>{const option=ativo.find(':selected');$('#local_unidade').val(option.data('local-unidade')||'');$('#locais_id').val(option.data('local-id')||'')};const agenda=()=>{$('#proxima_agenda').val(date($('#ultima_agenda').val(),parseInt($('#periodicidade').val(),10)))};const orcamento=()=>{$('#proximo_orcamento').val(date($('#proxima_agenda').val(),-parseInt($('#orcamento').val(),10)))};ativo.on('change',local);$('#ultima_agenda,#periodicidade').on('change input',()=>{agenda();orcamento()});$('#proxima_agenda,#orcamento').on('change input',orcamento);local()});
</script>@endpush
