@extends('layouts.app')
@section('title','Lançamentos da agenda')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
@php $equip=$agenda->equipamento; $localUnidade=($equip?->local?->titulo?:'Local não informado').' - '.($equip?->local?->unidade?->titulo?:'Unidade não informada'); $modalTitle='Etapas da Manutenção de '.($equip?->titulo?:'Ativo não informado').' - '.$localUnidade.' - Agendamento: '.($agenda->proxima_agenda?->format('d/m/Y')?:'não informado'); @endphp
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h1 class="page-title">Lançamentos da Agenda Preventiva</h1><p class="page-description mb-0">{{ $equip?->titulo?:'Ativo não informado' }} - {{ $localUnidade }}</p></div><a href="{{ route('agenda.index') }}" class="btn btn-outline-secondary align-self-start"><i class="bi bi-arrow-left me-1"></i>Voltar</a></div>
<section class="card content-card mb-4"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-3"><h5>Próximo agendamento</h5><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#etapasModal"><i class="bi bi-list-check me-1"></i>Etapas da manutenção</button></div><div class="card-body p-4"><div class="row g-3">
@foreach([['Ativo / Equipamento',($equip?->titulo?:'—').' ('.($equip?->codigo?:'sem código').')'],['Local - Unidade',$localUnidade],['Próxima agenda',$agenda->proxima_agenda?->format('d/m/Y')],['Data do orçamento',$agenda->proximo_orcamento?->format('d/m/Y')],['Periodicidade',$agenda->periodicidade!==null?$agenda->periodicidade.' dias':null],['Antecedência do orçamento',$agenda->orcamento!==null?$agenda->orcamento.' dias':null]] as [$label,$value])<div class="col-md-6 col-xl-4"><div class="form-label">{{ $label }}</div><div class="form-control bg-body-tertiary h-auto">{{ filled($value)?$value:'—' }}</div></div>@endforeach
</div></div></section>
<section class="card content-card"><div class="card-header"><h5>Lançamentos já ocorridos</h5></div><div class="card-body p-0"><div class="table-responsive"><table id="lancamentosTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Data do lançamento</th><th>Solicitante</th><th>Problema</th><th>Data do orçamento</th><th>Data do agendamento</th><th>Etapa</th><th>Status</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></div></section>
<div class="modal fade" id="etapasModal" tabindex="-1" aria-labelledby="etapasModalLabel" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="etapasModalLabel">{{ $modalTitle }}</h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button></div></div></div></div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>new DataTable('#lancamentosTable',{processing:true,serverSide:true,ajax:@json(route('agenda.lancamentos.data',$agenda,false)),order:[[1,'desc']],columns:[{data:'id'},{data:'data_lancamento'},{data:'solicitante'},{data:'problema'},{data:'data_orcamento'},{data:'data_agendamento'},{data:'etapa'},{data:'status',searchable:false},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',search:'Pesquisar:',lengthMenu:'Exibir _MENU_ registros',info:'Exibindo _START_ a _END_ de _TOTAL_ lançamentos',infoEmpty:'Nenhum lançamento encontrado',emptyTable:'Nenhum lançamento registrado',zeroRecords:'Nenhum registro encontrado',paginate:{first:'Primeira',last:'Última',next:'Próxima',previous:'Anterior'}}}));</script>@endpush
