@extends('layouts.app')
@section('title','Lançamentos da agenda')
@push('styles')
<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>.image-mode-option{cursor:pointer}.image-zone{min-height:170px;border:2px dashed var(--bs-border-color);transition:.2s ease}.image-zone:focus,.image-zone:hover{border-color:var(--bs-primary);background:var(--bs-primary-bg-subtle);outline:0}.image-zone.is-dragging{border-color:var(--bs-primary);background:var(--bs-primary-bg-subtle);transform:scale(1.01)}.foto-preview{max-width:220px;max-height:145px;object-fit:contain}.zone-icon{font-size:2rem;color:var(--bs-primary)}.despesa-fieldset{background:var(--bs-tertiary-bg);border-color:var(--bs-border-color-translucent)!important}.estoque-badge{font-size:.72rem;font-weight:600}.custo-total{font-weight:700;color:var(--bs-success-text-emphasis);background:var(--bs-success-bg-subtle)!important}.despesas-total-row th{background:var(--bs-primary-bg-subtle)!important;color:var(--bs-primary-text-emphasis);font-size:1rem;padding:.9rem 1rem!important}.despesas-total-valor{font-size:1.15rem}.agenda-resumo-card{border-top:3px solid var(--bs-primary)}.agenda-resumo-card .card-header{background:linear-gradient(90deg,var(--bs-primary-bg-subtle),transparent)}.resumo-value{min-height:42px;display:flex;align-items:center}.etapa-atual-box{min-height:42px;display:flex;align-items:center;justify-content:center;background:var(--bs-primary)!important;color:#fff!important;border-color:var(--bs-primary)!important;font-size:1.05rem;font-weight:700}.etapas-button{box-shadow:0 .25rem .75rem rgba(var(--bs-primary-rgb),.25);font-weight:600}</style>
@endpush
@section('content')
@php
    $equip = $proximoLancamento?->equipamento ?: $agenda->equipamento;
    $local = $equip?->local ?: $proximoLancamento?->local;
    $localUnidade = ($local?->titulo ?: 'Local não informado').' - '.($local?->unidade?->titulo ?: 'Unidade não informada');
    $equipamentoCompleto = ($equip?->titulo ?: 'Ativo não informado').' - '.$localUnidade;
    $dataAgendamento = $proximoLancamento?->data_agendamento ?: $agenda->proxima_agenda;
    $etapaAtual = max(1, (int) ($proximoLancamento?->etapa ?: 1));
    $quantidadeEtapas = max(4, $etapaAtual);
    $inicio = $proximoLancamento?->data_inicio ?: now();
    $tecnicoSelecionado = $proximoLancamento?->tecnicos_id ?: $usuarioId;
    $modalTitle = 'Etapas da Manutenção de '.$equipamentoCompleto.' - Agendamento: '.($dataAgendamento?->format('d/m/Y') ?: 'não informado');
    $lancamentosDataUrl = route('agenda.lancamentos.data', $agenda, false);
    $orcamentosDataUrl = $proximoLancamento ? route('agenda.lancamentos.orcamentos.data', [$agenda, $proximoLancamento], false) : null;
    $despesasDataUrl = $proximoLancamento ? route('agenda.lancamentos.despesas.data', [$agenda, $proximoLancamento], false) : null;
@endphp
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h1 class="page-title">Lançamentos da Agenda Preventiva</h1><p class="page-description mb-0">{{ $equip?->titulo?:'Ativo não informado' }} - {{ $localUnidade }}</p></div><a href="{{ route('agenda.index') }}" class="btn btn-outline-secondary align-self-start"><i class="bi bi-arrow-left me-1"></i>Voltar</a></div>
@if(session('status'))<div class="alert alert-success alert-dismissible fade show shadow-sm"><i class="bi bi-check-circle-fill me-2"></i><strong>{{ session('status') }}</strong><button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<section class="card content-card agenda-resumo-card mb-4"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h5 class="mb-1">Próximo agendamento</h5>@if($proximoLancamento)<small class="text-body-secondary">Lançamento #{{ $proximoLancamento->id }}</small>@endif</div><button class="btn btn-primary btn-lg etapas-button" data-bs-toggle="modal" data-bs-target="#etapasModal" @disabled(!$proximoLancamento)><i class="bi bi-list-check me-2"></i>Abrir etapas da manutenção</button></div><div class="card-body p-3">
@if(!$proximoLancamento)<div class="alert alert-info mb-0">Não há lançamento não arquivado para esta agenda.</div>@else<div class="row g-3"><div class="col-md-6"><div class="form-label mb-1">Ativo / Equipamento</div><div class="form-control bg-body-tertiary resumo-value text-break">{{ $equip?->titulo?:'—' }} ({{ $equip?->codigo?:'sem código' }})</div></div><div class="col-md-6"><div class="form-label mb-1">Local - Unidade</div><div class="form-control bg-body-tertiary resumo-value text-break">{{ $localUnidade }}</div></div><div class="col-6 col-lg-3"><div class="form-label mb-1">Periodicidade</div><div class="form-control bg-body-tertiary resumo-value">{{ $agenda->periodicidade!==null?$agenda->periodicidade.' dias':'—' }}</div></div><div class="col-6 col-lg-3"><div class="form-label mb-1">Próxima agenda</div><div class="form-control bg-body-tertiary resumo-value">{{ $agenda->proxima_agenda?->format('d/m/Y')?:'—' }}</div></div><div class="col-6 col-lg-3"><div class="form-label mb-1">Antecedência do orçamento</div><div class="form-control bg-body-tertiary resumo-value">{{ $agenda->orcamento!==null?$agenda->orcamento.' dias':'—' }}</div></div><div class="col-6 col-lg-3"><div class="form-label mb-1">Etapa atual</div><div class="form-control etapa-atual-box"><i class="bi bi-flag-fill me-2"></i>Etapa {{ $etapaAtual }}</div></div></div>@endif</div></section>
<section class="card content-card"><div class="card-header"><h5>Lançamentos Arquivados</h5></div><div class="card-body p-0"><div class="table-responsive"><table id="lancamentosTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Data do lançamento</th><th>Solicitante</th><th>Problema</th><th>Data do orçamento</th><th>Data do agendamento</th><th>Etapa</th><th>Status</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></div></section>
@if($proximoLancamento)
<div class="modal fade" id="etapasModal" tabindex="-1" aria-labelledby="etapasModalLabel" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="etapasModalLabel">{{ $modalTitle }}</h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button></div><div class="modal-body"><div id="modalFeedback"></div>
<div class="nav nav-pills gap-2 mb-4" role="tablist">@for($etapa=1;$etapa<=$quantidadeEtapas;$etapa++)<button class="nav-link @if($etapa===$etapaAtual) active @endif" id="etapa-{{ $etapa }}-tab" data-bs-toggle="pill" data-bs-target="#etapa-{{ $etapa }}" type="button" role="tab">Etapa {{ $etapa }}</button>@endfor</div><div class="tab-content">
<div class="tab-pane fade @if($etapaAtual===1) show active @endif" id="etapa-1" role="tabpanel"><div class="row g-3 mb-4"><div class="col-md-8"><label class="form-label">Equipamento/Patrimônio</label><input class="form-control" value="{{ $equipamentoCompleto }}" disabled></div><div class="col-md-4"><label class="form-label">Data do agendamento</label><input class="form-control" value="{{ $dataAgendamento?->format('d/m/Y H:i') ?: '—' }}" disabled></div></div>
<form id="orcamentoForm" action="{{ route('agenda.lancamentos.orcamentos.store', [$agenda,$proximoLancamento]) }}" method="post" enctype="multipart/form-data">@csrf<fieldset class="border rounded p-3 mb-4"><legend class="float-none w-auto px-2 fs-5">Cadastro de Requisição de Orçamento</legend><div class="row g-3"><div class="col-12"><label for="descricao" class="form-label">Requisição de Orçamento</label><textarea id="descricao" name="descricao" rows="4" class="form-control" required></textarea></div><div class="col-12"><label for="centro_custo" class="form-label">Centro de custo</label><input id="centro_custo" name="centro_custo" maxlength="50" class="form-control" required></div>
<div class="col-12"><label class="form-label d-block">Como deseja informar a imagem?</label><div class="d-flex flex-wrap gap-3"><label class="image-mode-option border rounded px-3 py-2"><input class="form-check-input me-2" type="radio" name="tipo_imagem" value="foto" checked>Enviar ou colar foto</label><label class="image-mode-option border rounded px-3 py-2"><input class="form-check-input me-2" type="radio" name="tipo_imagem" value="link">Usar link da internet</label></div></div>
<div id="linkFields" class="col-12 d-none"><label for="link" class="form-label">Link da foto do produto</label><input id="link" name="link" type="url" maxlength="300" class="form-control form-control-lg" placeholder="https://exemplo.com/foto-do-produto.jpg"><div class="form-text">Cole o endereço direto da imagem encontrada na internet.</div></div>
<div id="fotoFields" class="col-12"><label class="form-label">Foto do produto</label><input id="foto" name="foto" type="file" accept="image/*" class="visually-hidden"><div class="row g-3"><div class="col-md-6"><div id="fotoPaste" class="image-zone rounded p-4 d-flex flex-column justify-content-center align-items-center text-center h-100" tabindex="0"><i class="bi bi-clipboard-plus zone-icon mb-2"></i><strong>Cole uma foto</strong><span class="text-body-secondary mt-1">Clique nesta área e pressione</span><kbd class="mt-2">Ctrl + V</kbd></div></div><div class="col-md-6"><div id="fotoDrop" class="image-zone rounded p-4 d-flex flex-column justify-content-center align-items-center text-center h-100"><i class="bi bi-cloud-arrow-up zone-icon mb-2"></i><strong>Arraste a foto para cá</strong><span class="text-body-secondary my-2">ou</span><button id="selecionarFoto" type="button" class="btn btn-outline-primary"><i class="bi bi-folder2-open me-1"></i>Selecionar arquivo</button><small class="text-body-secondary mt-2">PNG, JPG ou WEBP • máximo 5 MB</small></div></div></div><div id="fotoSelected" class="alert alert-success d-none align-items-center gap-3 mt-3 mb-0"><img id="fotoPreview" class="foto-preview rounded" alt="Pré-visualização"><div><strong id="fotoNome" class="d-block"></strong><span>Foto pronta para ser enviada.</span><button id="removerFoto" type="button" class="btn btn-sm btn-link text-danger p-0 d-block">Remover foto</button></div></div></div>
<div class="col-12 text-end"><button class="btn btn-primary" type="submit"><i class="bi bi-floppy me-1"></i>Salvar</button></div></div></fieldset></form>
<fieldset class="border rounded p-3"><legend class="float-none w-auto px-2 fs-5">Requisições de Orçamento cadastradas</legend><div class="table-responsive"><table id="orcamentosTable" class="table table-hover align-middle w-100"><thead><tr><th>Descrição</th><th>Centro de Custo</th><th>Foto</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></fieldset><div class="d-flex justify-content-end border-top mt-4 pt-3"><button type="button" class="btn btn-primary ir-etapa" data-etapa="2">Próxima <i class="bi bi-arrow-right ms-1"></i></button></div></div>
<div class="tab-pane fade @if($etapaAtual===2) show active @endif" id="etapa-2" role="tabpanel"><form id="etapaDoisForm" action="{{ route('agenda.lancamentos.etapa-dois', [$agenda,$proximoLancamento]) }}">@csrf @method('PATCH')<div class="row g-3"><div class="col-md-8"><label class="form-label">Equipamento/Patrimônio</label><input class="form-control" value="{{ $equipamentoCompleto }}" disabled></div><div class="col-md-4"><label class="form-label">Data do agendamento</label><input class="form-control" value="{{ $dataAgendamento?->format('d/m/Y H:i') ?: '—' }}" disabled></div><div class="col-12"><label for="tecnicos_id" class="form-label">Técnico/Responsável</label><select id="tecnicos_id" name="tecnicos_id" class="form-select" @disabled(!$supervisor)>@foreach($tecnicos as $tecnico)<option value="{{ $tecnico->id }}" @selected((int)$tecnicoSelecionado===(int)$tecnico->id)>{{ $tecnico->nome }}</option>@endforeach</select>@unless($supervisor)<input type="hidden" name="tecnicos_id" value="{{ $usuarioId }}">@endunless</div><div class="col-md-4"><label for="data_inicio" class="form-label">Data de Início</label><input id="data_inicio" name="data_inicio" type="date" class="form-control form-control-lg" value="{{ $inicio->format('Y-m-d') }}" required></div><div class="col-md-4"><label for="hora_inicio" class="form-label">Hora de Início</label><input id="hora_inicio" name="hora_inicio" type="time" class="form-control form-control-lg" value="{{ $inicio->format('H:i') }}" required></div><div class="col-md-4 d-flex align-items-end"><button id="marcarInicio" type="button" class="btn btn-outline-primary btn-lg w-100"><i class="bi bi-clock me-1"></i>Horário de início</button></div></div><div class="d-flex justify-content-end border-top mt-4 pt-3"><button type="submit" class="btn btn-primary">Salvar e próxima <i class="bi bi-arrow-right ms-1"></i></button></div></form></div>
<div class="tab-pane fade @if($etapaAtual===3) show active @endif" id="etapa-3" role="tabpanel"><div class="row g-3 mb-4"><div class="col-md-8"><label class="form-label">Equipamento/Patrimônio</label><input class="form-control" value="{{ $equipamentoCompleto }}" disabled></div><div class="col-md-4"><label class="form-label">Data do agendamento</label><input class="form-control" value="{{ $dataAgendamento?->format('d/m/Y H:i') ?: '—' }}" disabled></div></div>
<form id="despesaForm" action="{{ route('agenda.lancamentos.despesas.store', [$agenda,$proximoLancamento]) }}">@csrf<fieldset class="despesa-fieldset border rounded-3 p-4 mb-4"><legend class="float-none w-auto px-2 fs-5 fw-semibold"><i class="bi bi-cart-plus me-2 text-primary"></i>Cadastro de Despesas da Manutenção</legend><div class="row g-3 align-items-end"><div class="col-lg-6"><label for="compra_id" class="form-label fw-semibold">Produto, preços e estoque disponível</label><select id="compra_id" name="compra_id" class="form-select" required><option value="">Selecione ou pesquise um produto</option>@foreach($compras as $compra)@php $estoque=max(0,((float)$compra->quantidade*(float)$compra->quantidade_unitaria)-(float)$compra->qtde_utilizada); @endphp<option value="{{ $compra->id }}" data-preco="{{ $compra->preco_unitario }}" data-unidade="{{ $compra->unidade }}" data-estoque="{{ $estoque }}">{{ $compra->titulo }} - Unit. R$ {{ number_format((float)$compra->preco_unitario,2,',','.') }}/{{ $compra->unidade }} • Pacote R$ {{ number_format((float)$compra->preco,2,',','.') }} • Estoque {{ rtrim(rtrim(number_format($estoque,2,',','.'),'0'),',') }} {{ $compra->unidade }}</option>@endforeach</select></div><div class="col-sm-4 col-lg-2"><label for="quantidade_despesa" class="form-label fw-semibold d-flex justify-content-between align-items-center gap-1"><span>Qtde. unit.</span><span id="estoqueDespesa" class="badge text-bg-info estoque-badge d-none"></span></label><div class="input-group"><input id="quantidade_despesa" name="quantidade" type="number" min="0.1" step="0.1" class="form-control" required><span id="unidadeDespesa" class="input-group-text">—</span></div></div><div class="col-sm-4 col-lg-2"><label for="custo_despesa" class="form-label fw-semibold">Custo total</label><input id="custo_despesa" class="form-control custo-total" value="R$ 0,00" readonly></div><div class="col-sm-4 col-lg-2"><label class="form-label fw-semibold">Ações</label><button class="btn btn-primary w-100" type="submit"><i class="bi bi-plus-circle me-1"></i>Adicionar</button></div></div></fieldset></form>
<fieldset class="border rounded-3 p-4"><legend class="float-none w-auto px-2 fs-5 fw-semibold"><i class="bi bi-receipt me-2 text-primary"></i>Despesas cadastradas</legend><div class="table-responsive"><table id="despesasTable" class="table table-hover align-middle w-100 mb-0"><thead class="table-light"><tr><th>Produto</th><th>Qtde.</th><th>Un.</th><th>Custo unitário</th><th>Subtotal</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody><tfoot><tr class="despesas-total-row"><th colspan="4" class="text-end">Total geral das despesas</th><th id="totalGeralDespesas" class="despesas-total-valor">R$ 0,00</th><th></th></tr></tfoot></table></div></fieldset><div class="d-flex justify-content-end border-top mt-4 pt-3"><button type="button" class="btn btn-primary ir-etapa" data-etapa="4">Próxima <i class="bi bi-arrow-right ms-1"></i></button></div></div>
<div class="tab-pane fade @if($etapaAtual===4) show active @endif" id="etapa-4" role="tabpanel"><div class="row g-3 mb-4"><div class="col-md-8"><label class="form-label">Equipamento/Patrimônio</label><input class="form-control" value="{{ $equipamentoCompleto }}" disabled></div><div class="col-md-4"><label class="form-label">Data do agendamento</label><input class="form-control" value="{{ $dataAgendamento?->format('d/m/Y H:i') ?: '—' }}" disabled></div></div><form id="conclusaoForm" action="{{ route('agenda.lancamentos.concluir', [$agenda,$proximoLancamento]) }}">@csrf<fieldset class="border rounded-3 p-4"><legend class="float-none w-auto px-2 fs-5 fw-semibold"><i class="bi bi-check2-circle me-2 text-success"></i>Conclusão da Manutenção</legend><div class="row g-3"><div class="col-12"><label for="situacao_id" class="form-label fw-semibold">Situação da Manutenção</label><select id="situacao_id" name="situacao_id" class="form-select" required><option value="">Selecione uma situação</option>@foreach($situacoes as $situacao)<option value="{{ $situacao->id }}" @selected((int)$proximoLancamento->situacao_id===(int)$situacao->id)>{{ $situacao->titulo }}</option>@endforeach</select></div><div class="col-12"><label for="observacao_conclusao" class="form-label fw-semibold">Observação</label><textarea id="observacao_conclusao" name="observacao" rows="3" maxlength="512" class="form-control">{{ $proximoLancamento->observacao }}</textarea></div></div></fieldset><div class="d-flex justify-content-end border-top mt-4 pt-3"><button type="submit" class="btn btn-success btn-lg"><i class="bi bi-archive me-2"></i>Salvar e arquivar</button></div></form></div>
@for($etapa=5;$etapa<=$quantidadeEtapas;$etapa++)<div class="tab-pane fade @if($etapaAtual===$etapa) show active @endif" id="etapa-{{ $etapa }}" role="tabpanel"><div class="alert alert-info mb-0">A etapa {{ $etapa }} será detalhada posteriormente.</div></div>@endfor
</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button></div></div></div></div>
@endif
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{const language={processing:'Carregando...',search:'Pesquisar:',lengthMenu:'Exibir _MENU_ registros',info:'Exibindo _START_ a _END_ de _TOTAL_ registros',infoEmpty:'Nenhum registro encontrado',emptyTable:'Nenhum registro cadastrado',zeroRecords:'Nenhum registro encontrado',paginate:{first:'Primeira',last:'Última',next:'Próxima',previous:'Anterior'}};new DataTable('#lancamentosTable',{processing:true,serverSide:true,ajax:@json($lancamentosDataUrl),order:[[1,'desc']],columns:[{data:'id'},{data:'data_lancamento'},{data:'solicitante'},{data:'problema'},{data:'data_orcamento'},{data:'data_agendamento'},{data:'etapa'},{data:'status',searchable:false},{data:'acoes',orderable:false,searchable:false}],language});
@if($proximoLancamento)
const csrf=@json(csrf_token()),feedback=document.getElementById('modalFeedback'),message=(text,type='success')=>feedback.innerHTML=`<div class="alert alert-${type} alert-dismissible fade show">${text}<button class="btn-close" data-bs-dismiss="alert"></button></div>`,errors=async response=>{const body=await response.json().catch(()=>({}));throw new Error(body.message||Object.values(body.errors||{}).flat().join('<br>')||'Não foi possível concluir a operação.')};const orcamentos=new DataTable('#orcamentosTable',{ajax:{url:@json($orcamentosDataUrl),dataSrc:'data'},order:[],columns:[{data:'descricao'},{data:'centro_custo'},{data:'foto',orderable:false,searchable:false},{data:'acoes',orderable:false,searchable:false}],language}),despesas=new DataTable('#despesasTable',{ajax:{url:@json($despesasDataUrl),dataSrc:'data'},paging:false,lengthChange:false,info:false,order:[],columns:[{data:'produto'},{data:'quantidade'},{data:'unidade'},{data:'custo'},{data:'subtotal'},{data:'acoes',orderable:false,searchable:false}],footerCallback:function(){const total=this.api().rows({search:'applied'}).data().toArray().reduce((sum,row)=>sum+Number(row.subtotal_valor||0),0);document.getElementById('totalGeralDespesas').textContent=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(total)},language});$('#tecnicos_id,#compra_id,#situacao_id').select2({theme:'bootstrap-5',width:'100%',dropdownParent:$('#etapasModal'),placeholder:'Selecione ou pesquise'});document.getElementById('etapasModal').addEventListener('shown.bs.modal',()=>{orcamentos.columns.adjust();despesas.columns.adjust()});document.querySelectorAll('.ir-etapa').forEach(button=>button.addEventListener('click',()=>bootstrap.Tab.getOrCreateInstance(document.getElementById(`etapa-${button.dataset.etapa}-tab`)).show()));
const foto=document.getElementById('foto'),paste=document.getElementById('fotoPaste'),drop=document.getElementById('fotoDrop'),preview=document.getElementById('fotoPreview'),selected=document.getElementById('fotoSelected'),fotoNome=document.getElementById('fotoNome'),link=document.getElementById('link'),fotoFields=document.getElementById('fotoFields'),linkFields=document.getElementById('linkFields');
const clearFoto=()=>{foto.value='';preview.removeAttribute('src');selected.classList.add('d-none');selected.classList.remove('d-flex')},setFoto=file=>{if(!file||!file.type.startsWith('image/')){message('Selecione ou cole um arquivo de imagem válido.','warning');return}if(file.size>5242880){message('A foto deve ter no máximo 5 MB.','warning');return}const transfer=new DataTransfer();transfer.items.add(file);foto.files=transfer.files;preview.src=URL.createObjectURL(file);fotoNome.textContent=file.name||'Imagem colada';selected.classList.remove('d-none');selected.classList.add('d-flex')};
const imageMode=()=>{const mode=document.querySelector('[name="tipo_imagem"]:checked').value,isFoto=mode==='foto';fotoFields.classList.toggle('d-none',!isFoto);linkFields.classList.toggle('d-none',isFoto);foto.disabled=!isFoto;link.disabled=isFoto;if(isFoto)link.value='';else clearFoto()};document.querySelectorAll('[name="tipo_imagem"]').forEach(radio=>radio.addEventListener('change',imageMode));imageMode();
document.getElementById('selecionarFoto').addEventListener('click',()=>foto.click());document.getElementById('removerFoto').addEventListener('click',clearFoto);foto.addEventListener('change',()=>setFoto(foto.files[0]));paste.addEventListener('paste',event=>{event.preventDefault();const file=[...event.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();setFoto(file)});drop.addEventListener('dragover',event=>{event.preventDefault();drop.classList.add('is-dragging')});drop.addEventListener('dragleave',()=>drop.classList.remove('is-dragging'));drop.addEventListener('drop',event=>{event.preventDefault();drop.classList.remove('is-dragging');setFoto(event.dataTransfer.files[0])});
document.getElementById('orcamentoForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:new FormData(form)});if(!response.ok)await errors(response);const body=await response.json();form.reset();clearFoto();imageMode();orcamentos.ajax.reload();message(body.message)}catch(error){message(error.message,'danger')}finally{button.disabled=false}});document.getElementById('orcamentosTable').addEventListener('click',async event=>{const button=event.target.closest('.excluir-orcamento');if(!button||!confirm('Excluir esta requisição de orçamento?'))return;try{const response=await fetch(button.dataset.url,{method:'DELETE',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf}});if(!response.ok)await errors(response);orcamentos.ajax.reload();message((await response.json()).message)}catch(error){message(error.message,'danger')}});
const produto=document.getElementById('compra_id'),quantidadeDespesa=document.getElementById('quantidade_despesa'),custoDespesa=document.getElementById('custo_despesa'),unidadeDespesa=document.getElementById('unidadeDespesa'),estoqueDespesa=document.getElementById('estoqueDespesa'),currency=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0),calculateCusto=()=>{const preco=Number(produto.selectedOptions[0]?.dataset.preco||0),quantidade=Number(quantidadeDespesa.value||0);custoDespesa.value=currency(preco*quantidade)};const updateProduto=()=>{const option=produto.selectedOptions[0],unidade=option?.dataset.unidade||'',estoque=Number(option?.dataset.estoque||0);quantidadeDespesa.step=unidade==='un'?'1':'0.1';quantidadeDespesa.min=unidade==='un'?'1':'0.1';quantidadeDespesa.max=estoque||'';unidadeDespesa.textContent=unidade||'—';estoqueDespesa.textContent=option?.value?`${estoque.toLocaleString('pt-BR')} ${unidade} disponíveis`:'';estoqueDespesa.classList.toggle('d-none',!option?.value);calculateCusto()};const updateEstoque=(id,estoque)=>{const option=produto.querySelector(`option[value="${id}"]`);if(!option||estoque===null)return;const value=produto.value;option.dataset.estoque=estoque;option.textContent=option.textContent.replace(/Estoque [^•]+$/,`Estoque ${Number(estoque).toLocaleString('pt-BR')} ${option.dataset.unidade}`);$(produto).select2('destroy').select2({theme:'bootstrap-5',width:'100%',dropdownParent:$('#etapasModal'),placeholder:'Selecione ou pesquise'}).val(value).trigger('change.select2');updateProduto()};$(produto).on('change',updateProduto);quantidadeDespesa.addEventListener('input',calculateCusto);updateProduto();
document.getElementById('despesaForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:new FormData(form)});if(!response.ok)await errors(response);const body=await response.json();updateEstoque(body.compra_id,body.estoque);quantidadeDespesa.value='';despesas.ajax.reload();message(body.message)}catch(error){message(error.message,'danger')}finally{button.disabled=false}});document.getElementById('despesasTable').addEventListener('click',async event=>{const button=event.target.closest('.excluir-despesa');if(!button||!confirm('Excluir esta despesa e devolver a quantidade ao estoque?'))return;try{const response=await fetch(button.dataset.url,{method:'DELETE',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf}});if(!response.ok)await errors(response);const body=await response.json();updateEstoque(body.compra_id,body.estoque);despesas.ajax.reload();message(body.message)}catch(error){message(error.message,'danger')}});
const etapaDoisForm=document.getElementById('etapaDoisForm'),dataInicio=document.getElementById('data_inicio'),horaInicio=document.getElementById('hora_inicio'),marcarInicio=document.getElementById('marcarInicio');let inicioSalvo=@json((bool)$proximoLancamento->data_inicio);const now=()=>{const date=new Date(),part=value=>String(value).padStart(2,'0');dataInicio.value=`${date.getFullYear()}-${part(date.getMonth()+1)}-${part(date.getDate())}`;horaInicio.value=`${part(date.getHours())}:${part(date.getMinutes())}`};const saveEtapaDois=async(avancar,button)=>{button.disabled=true;try{const response=await fetch(etapaDoisForm.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:new FormData(etapaDoisForm)});if(!response.ok)await errors(response);inicioSalvo=true;horaInicio.classList.remove('is-invalid');message((await response.json()).message);if(avancar)bootstrap.Tab.getOrCreateInstance(document.getElementById('etapa-3-tab')).show()}catch(error){message(error.message,'danger')}finally{button.disabled=false}};marcarInicio.addEventListener('click',()=>{now();saveEtapaDois(false,marcarInicio)});etapaDoisForm.addEventListener('submit',event=>{event.preventDefault();saveEtapaDois(true,etapaDoisForm.querySelector('[type=submit]'))});document.querySelectorAll('#etapa-3-tab,#etapa-4-tab').forEach(tab=>tab.addEventListener('click',event=>{if(inicioSalvo)return;event.preventDefault();event.stopImmediatePropagation();bootstrap.Tab.getOrCreateInstance(document.getElementById('etapa-2-tab')).show();horaInicio.classList.add('is-invalid');message('Registre e salve o horário de início antes de avançar para a próxima etapa.','warning');setTimeout(()=>{horaInicio.focus();horaInicio.select()},150)}));
document.getElementById('conclusaoForm').addEventListener('submit',async event=>{event.preventDefault();if(!confirm('Confirma a conclusão e o arquivamento desta manutenção?'))return;const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:new FormData(form)});if(!response.ok)await errors(response);const body=await response.json();window.location.href=body.redirect}catch(error){message(error.message,'danger');button.disabled=false}});
@endif});</script>
@endpush
