@extends('layouts.app')
@section('title','Manutenções')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>
.manutencao-page{padding:1rem}.filtros-scroll{overflow-x:auto;scrollbar-width:thin}.filtros-scroll .nav{min-width:max-content}.manutencao-grid{display:grid;grid-template-columns:1fr;gap:.85rem}.manutencao-card{cursor:pointer;border:0;border-left:5px solid;box-shadow:0 .25rem .85rem rgba(16,24,40,.09);transition:transform .18s ease,box-shadow .18s ease;min-width:0;overflow:hidden;border-radius:.8rem}.manutencao-card::after{content:"";position:absolute;inset:0 0 auto 0;height:3px;background:currentColor;opacity:.18}.manutencao-card .card-body{display:flex;flex-direction:column;min-height:205px;padding:1rem}.manutencao-card:hover,.manutencao-card:focus-visible{transform:translateY(-4px);box-shadow:0 .65rem 1.35rem rgba(16,24,40,.16);outline:2px solid var(--bs-primary);outline-offset:2px}.status-nao-iniciada{border-color:var(--bs-secondary);background:linear-gradient(145deg,var(--bs-secondary-bg-subtle),var(--bs-body-bg) 72%)}.status-em-manutencao{border-color:var(--bs-warning);background:linear-gradient(145deg,var(--bs-warning-bg-subtle),var(--bs-body-bg) 72%)}.status-arquivada{border-color:var(--bs-success);background:linear-gradient(145deg,var(--bs-success-bg-subtle),var(--bs-body-bg) 72%)}.card-equipment{font-size:1rem;line-height:1.25;color:var(--bs-emphasis-color)}.card-meta{font-size:.79rem;line-height:1.35}.card-meta i{width:1rem;display:inline-block;text-align:center}.status-chip{font-size:.68rem;white-space:normal;text-align:center;line-height:1.2;padding:.38rem .48rem;max-width:46%}.pecas-toggle{margin-top:auto!important}.pecas-lista{font-size:.73rem;line-height:1.45;background:rgba(var(--bs-body-bg-rgb),.8);border:1px solid var(--bs-border-color)}.timer-display{font-variant-numeric:tabular-nums;letter-spacing:.03em}.modal-total{background:var(--bs-danger-bg-subtle);color:var(--bs-danger-text-emphasis);border-color:rgba(var(--bs-danger-rgb),.3)!important}.modal-section{display:none}.modal-section.active{display:block}.readonly-note{font-size:.8rem}.despesa-row{font-size:.82rem}.despesa-editor{background:linear-gradient(135deg,var(--bs-tertiary-bg),var(--bs-body-bg));border-color:var(--bs-border-color)!important}.despesa-editor legend{font-size:1rem}.estoque-badge{font-size:.7rem}.custo-preview{font-weight:700;color:var(--bs-danger-text-emphasis);background:var(--bs-danger-bg-subtle)!important;border-color:rgba(var(--bs-danger-rgb),.3)!important}.select2-container--bootstrap-5 .select2-selection{min-height:42px}.despesas-header{background:var(--bs-primary-bg-subtle);color:var(--bs-primary-text-emphasis)}
@media(min-width:576px){.manutencao-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}}
@media(min-width:992px){.manutencao-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(min-width:1400px){.manutencao-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:1.15rem}.manutencao-page{padding:1.5rem 2rem}}
@media(max-width:575.98px){.manutencao-page{padding:.75rem}.manutencao-card .card-body{min-height:auto;padding:.9rem}.status-chip{max-width:44%}}
</style>
@endpush
@section('content')
@php
    $itens = [];
@endphp
<div class="manutencao-page container-fluid">
    <div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h1 class="h3 mb-1">Manutenções preventivas</h1><p class="text-body-secondary mb-0">Acompanhe, execute e conclua os agendamentos.</p></div><a href="{{ url('/') }}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-left"></i><span class="d-none d-sm-inline ms-1">Voltar</span></a></div>
    <nav class="filtros-scroll mb-3" aria-label="Filtrar manutenções"><div class="nav nav-pills flex-nowrap gap-2">
        @foreach(['hoje'=>'Hoje','7dias'=>'Próximos 7 dias','30dias'=>'Próximos 30 dias','todas'=>'Todas'] as $valor=>$rotulo)
            <a href="{{ route('manutencao.index',['filtro'=>$valor]) }}" class="nav-link @if($filtro===$valor) active @endif">{{ $rotulo }}</a>
        @endforeach
    </div></nav>

    @if($lancamentos->isEmpty())<div class="alert alert-info"><i class="bi bi-calendar2-check me-2"></i>Nenhuma manutenção encontrada neste período.</div>@endif
    <div class="manutencao-grid">
    @foreach($lancamentos as $lancamento)
        @php
            $equipamento=$lancamento->equipamento;
            $local=$equipamento?->local?:$lancamento->local;
            $localNome=($local?->titulo?:'Local não informado').' - '.($local?->unidade?->titulo?:'Unidade não informada');
            $arquivada=(bool)$lancamento->data_arquivamento;
            $iniciada=(bool)$lancamento->data_inicio;
            $status=$arquivada?'Manutenção arquivada':($iniciada?'Em manutenção':'Não iniciada');
            $statusClass=$arquivada?'arquivada':($iniciada?'em-manutencao':'nao-iniciada');
            $statusIcon=$arquivada?'bi-archive-fill':($iniciada?'bi-stopwatch-fill':'bi-hourglass-split');
            $dias=$lancamento->data_agendamento?now()->startOfDay()->diffInDays($lancamento->data_agendamento->copy()->startOfDay(),false):null;
            $prazo=$dias===null?'—':($dias>=0?'falta '.$dias.' dia(s)':'atrasado '.abs($dias).' dia(s)');
            $despesas=$lancamento->despesas->map(fn($d)=>['id'=>$d->id,'produto'=>$d->compra?->titulo?:'Produto não encontrado','quantidade'=>$d->quantidade,'unidade'=>$d->unidade?:'—','custo'=>(float)$d->custo,'subtotal'=>(float)$d->quantidade*(float)$d->custo]);
            $total=(float)($lancamento->total_despesas??$despesas->sum('subtotal'));
            $itens[$lancamento->id]=[
                'id'=>$lancamento->id,'equipamento'=>($equipamento?->titulo?:'Equipamento não informado').' ('.($equipamento?->codigo?:'sem código').')','local'=>$localNome,
                'agendamento'=>$lancamento->data_agendamento?->format('d/m/Y H:i')?:'—','prazo'=>$prazo,'status'=>$status,'statusClass'=>$statusClass,
                'inicio'=>$lancamento->data_inicio?->toIso8601String(),'fim'=>$lancamento->data_arquivamento?->toIso8601String(),'tecnico'=>$lancamento->tecnico?->nome?:'—',
                'situacao'=>$lancamento->situacao?->titulo,'observacao'=>$lancamento->observacao,'etapa'=>(int)$lancamento->etapa,'arquivada'=>$arquivada,'iniciada'=>$iniciada,
                'despesas'=>$despesas->values(),'total'=>$total,'startUrl'=>route('manutencao.iniciar',$lancamento,false),'viewExpensesUrl'=>route('manutencao.despesas.visualizar',$lancamento,false),
                'expenseUrl'=>route('manutencao.despesas.store',$lancamento,false),'finishUrl'=>route('manutencao.concluir',$lancamento,false),
            ];
        @endphp
        <article class="card manutencao-card status-{{ $statusClass }}" tabindex="{{ $podeVisualizar?0:-1 }}" data-id="{{ $lancamento->id }}" @unless($podeVisualizar) aria-disabled="true" @endunless>
            <div class="card-body">
                <div class="d-flex align-items-start justify-content-between gap-2 mb-2"><strong class="card-equipment text-break">{{ $equipamento?->titulo?:'Equipamento não informado' }}</strong><span class="badge status-chip text-bg-{{ $arquivada?'success':($iniciada?'warning':'secondary') }}"><i class="bi {{ $statusIcon }} me-1"></i>{{ $status }}</span></div>
                <div class="card-meta text-body-secondary mb-1"><i class="bi bi-geo-alt me-1"></i>{{ $localNome }}</div>
                <div class="card-meta"><i class="bi bi-calendar-event me-1"></i>{{ $lancamento->data_agendamento?->format('d/m/Y H:i')?:'—' }}</div>
                <div class="card-meta fw-semibold mt-1"><i class="bi bi-hourglass me-1"></i>{{ $prazo }}</div>
                @if($iniciada)<div class="card-meta mt-2"><i class="bi bi-person-gear me-1"></i>{{ $lancamento->tecnico?->nome?:'Técnico não informado' }}</div><div class="card-meta fw-bold timer-display mt-1" data-start="{{ $lancamento->data_inicio?->toIso8601String() }}" data-end="{{ $lancamento->data_arquivamento?->toIso8601String() }}"><i class="bi bi-stopwatch me-1"></i><span>00:00:00</span></div>@endif
                @if($despesas->isNotEmpty())<button type="button" class="btn btn-sm btn-outline-secondary w-100 mt-2 pecas-toggle" aria-expanded="false"><i class="bi bi-tools me-1"></i>{{ $despesas->count() }} peça(s) <i class="bi bi-chevron-down ms-1"></i></button><div class="pecas-lista rounded p-2 mt-1 d-none">@foreach($despesas as $despesa)<div>{{ $despesa['produto'] }} — {{ rtrim(rtrim(number_format($despesa['quantidade'],2,',','.'),'0'),',') }} {{ $despesa['unidade'] }}</div>@endforeach</div>@endif
            </div>
        </article>
    @endforeach
    </div>
    @if(method_exists($lancamentos,'links'))<div class="mt-4">{{ $lancamentos->links() }}</div>@endif
</div>

<div class="modal fade" id="manutencaoModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content">
    <div class="modal-header"><div><h5 id="modalEquipamento" class="modal-title"></h5><small id="modalLocal" class="text-body-secondary"></small></div><button class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button></div>
    <div class="modal-body"><div id="modalFeedback"></div>
        <div class="row g-2 mb-3"><div class="col-6"><div class="rounded border p-2 h-100"><small class="text-body-secondary d-block">Tempo decorrido</small><strong id="modalTimer" class="timer-display fs-5">00:00:00</strong></div></div><div class="col-6"><div class="modal-total rounded border p-2 h-100"><small class="d-block">Total gasto</small><strong id="modalTotal" class="fs-5">R$ 0,00</strong></div></div></div>
        <div class="nav nav-pills gap-2 mb-3"><button class="nav-link active modal-nav" data-section="resumo"><i class="bi bi-info-circle me-1"></i>Resumo</button><button id="navDespesas" class="nav-link modal-nav" data-section="despesas"><i class="bi bi-cart-plus me-1"></i>Despesas</button><button id="navConclusao" class="nav-link modal-nav" data-section="conclusao"><i class="bi bi-check2-circle me-1"></i>Conclusão</button></div>
        <section id="section-resumo" class="modal-section active"><dl class="row mb-0"><dt class="col-5">Agendamento</dt><dd id="modalAgendamento" class="col-7"></dd><dt class="col-5">Prazo</dt><dd id="modalPrazo" class="col-7"></dd><dt class="col-5">Status</dt><dd id="modalStatus" class="col-7"></dd><dt class="col-5">Técnico</dt><dd id="modalTecnico" class="col-7"></dd><dt class="col-5">Situação final</dt><dd id="modalSituacao" class="col-7"></dd></dl><p id="readonlyNote" class="alert alert-secondary readonly-note mt-3 mb-0 d-none">Visualização somente leitura.</p></section>
        <section id="section-despesas" class="modal-section">
            @if($podeEditar)<form id="despesaForm"><fieldset class="despesa-editor border rounded-3 p-3 mb-3"><legend class="float-none w-auto px-2 fw-semibold"><i class="bi bi-cart-plus me-2 text-primary"></i>Adicionar despesa</legend><div class="row g-3 align-items-end"><div class="col-12"><label for="manutencaoCompra" class="form-label fw-semibold">Produto, preços e estoque disponível</label><select id="manutencaoCompra" name="compra_id" class="form-select" required><option value="">Selecione ou pesquise um produto</option>@foreach($compras as $compra)@php($estoque=max(0,(float)$compra->quantidade*(float)$compra->quantidade_unitaria-(float)$compra->qtde_utilizada))<option value="{{ $compra->id }}" data-preco="{{ $compra->preco_unitario }}" data-unidade="{{ $compra->unidade }}" data-estoque="{{ $estoque }}">{{ $compra->titulo }} - Unit. R$ {{ number_format((float)$compra->preco_unitario,2,',','.') }}/{{ $compra->unidade }} • Pacote R$ {{ number_format((float)$compra->preco,2,',','.') }} • Estoque {{ rtrim(rtrim(number_format($estoque,2,',','.'),'0'),',') }} {{ $compra->unidade }}</option>@endforeach</select></div><div class="col-12 col-sm-5"><label for="manutencaoQuantidade" class="form-label fw-semibold d-flex justify-content-between gap-2"><span>Quantidade</span><span id="manutencaoEstoque" class="badge text-bg-info estoque-badge d-none"></span></label><div class="input-group"><input id="manutencaoQuantidade" name="quantidade" type="number" min="0.1" step="0.1" class="form-control" required><span id="manutencaoUnidade" class="input-group-text">—</span></div></div><div class="col-7 col-sm-4"><label for="manutencaoCusto" class="form-label fw-semibold">Custo total</label><input id="manutencaoCusto" class="form-control custo-preview" value="R$ 0,00" readonly></div><div class="col-5 col-sm-3"><label class="form-label fw-semibold">Ação</label><button class="btn btn-primary w-100" type="submit"><i class="bi bi-plus-circle me-1"></i><span class="d-none d-sm-inline">Adicionar</span></button></div></div></fieldset></form>@endif
            <div class="despesas-header rounded-top border px-3 py-2 fw-semibold"><i class="bi bi-receipt me-2"></i>Despesas cadastradas</div><div id="despesasLista" class="list-group list-group-flush border border-top-0 rounded-bottom"></div><div id="semDespesas" class="text-body-secondary text-center border border-top-0 rounded-bottom py-3"><i class="bi bi-inbox d-block fs-4 mb-1"></i>Nenhuma despesa adicionada.</div>
        </section>
        <section id="section-conclusao" class="modal-section"><div id="conclusaoBloqueada" class="alert alert-warning">Visite a tela de despesas antes de concluir a manutenção.</div>@if($podeEditar)<form id="conclusaoForm"><label class="form-label">Situação da manutenção</label><select name="situacao_id" class="form-select mb-3" required><option value="">Selecione</option>@foreach($situacoes as $situacao)<option value="{{ $situacao->id }}">{{ $situacao->titulo }}</option>@endforeach</select><label class="form-label">Observação</label><textarea name="observacao" maxlength="512" rows="3" class="form-control mb-3"></textarea><button class="btn btn-success w-100"><i class="bi bi-archive me-1"></i>Concluir e arquivar</button></form>@endif<div id="conclusaoLeitura" class="d-none"><strong id="conclusaoSituacao"></strong><p id="conclusaoObservacao" class="mb-0 mt-2"></p></div></section>
    </div>
</div></div></div>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const items=@json($itens); const canView=@json($podeVisualizar); const canEdit=@json($podeEditar); const filtro=@json($filtro); const csrf=@json(csrf_token()); let current=null;
 const modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('manutencaoModal')); const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const duration=(start,end)=>{if(!start)return'00:00:00';const seconds=Math.max(0,Math.floor((new Date(end||Date.now())-new Date(start))/1000));const h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');return`${h}:${m}:${s}`};
 const feedback=(message,type='success')=>document.getElementById('modalFeedback').innerHTML=message?`<div class="alert alert-${type} py-2">${message}</div>`:'';
 const request=async(url,options={})=>{const response=await fetch(url,{...options,headers:{Accept:'application/json','X-CSRF-TOKEN':csrf,...options.headers}});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.message||Object.values(json.errors||{}).flat().join(' ')||'Não foi possível concluir a operação.');return json};
 const produto=document.getElementById('manutencaoCompra'),quantidade=document.getElementById('manutencaoQuantidade'),custo=document.getElementById('manutencaoCusto'),unidade=document.getElementById('manutencaoUnidade'),estoqueBadge=document.getElementById('manutencaoEstoque');
 const calculateCost=()=>{if(custo)custo.value=money(Number(produto?.selectedOptions[0]?.dataset.preco||0)*Number(quantidade?.value||0))};
 const updateProduct=()=>{if(!produto)return;const option=produto.selectedOptions[0],unit=option?.dataset.unidade||'',stock=Number(option?.dataset.estoque||0);quantidade.step=unit==='un'?'1':'0.1';quantidade.min=unit==='un'?'1':'0.1';quantidade.max=option?.value?stock:'';unidade.textContent=unit||'—';estoqueBadge.textContent=option?.value?`${stock.toLocaleString('pt-BR')} ${unit} disponíveis`:'';estoqueBadge.classList.toggle('d-none',!option?.value);calculateCost()};
 const updateStock=(id,stock)=>{if(!produto||stock===null)return;const option=produto.querySelector(`option[value="${id}"]`);if(!option)return;option.dataset.estoque=stock;option.textContent=option.textContent.replace(/Estoque [^•]+$/,`Estoque ${Number(stock).toLocaleString('pt-BR')} ${option.dataset.unidade}`);const value=produto.value;$(produto).select2('destroy').select2({theme:'bootstrap-5',width:'100%',dropdownParent:$('#manutencaoModal'),placeholder:'Selecione ou pesquise um produto',language:{noResults:()=> 'Nenhum produto encontrado'}}).val(value).trigger('change.select2');updateProduct()};
 if(produto){$(produto).select2({theme:'bootstrap-5',width:'100%',dropdownParent:$('#manutencaoModal'),placeholder:'Selecione ou pesquise um produto',language:{noResults:()=> 'Nenhum produto encontrado'}}).on('change',updateProduct);quantidade.addEventListener('input',calculateCost);updateProduct()}
 const renderExpenses=()=>{const list=document.getElementById('despesasLista');list.innerHTML='';document.getElementById('semDespesas').classList.toggle('d-none',current.despesas.length>0);current.despesas.forEach(d=>{const row=document.createElement('div');row.className='list-group-item d-flex justify-content-between align-items-center gap-2 despesa-row';row.innerHTML=`<div><strong>${String(d.produto).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</strong><br>${d.quantidade} ${d.unidade} · ${money(d.subtotal)}</div>${canEdit&&!current.arquivada?`<button class="btn btn-sm btn-outline-danger remove-expense" data-id="${d.id}"><i class="bi bi-trash"></i></button>`:''}`;list.append(row)});document.getElementById('modalTotal').textContent=money(current.total)};
 const updateTimer=()=>{document.querySelectorAll('[data-start]').forEach(el=>el.querySelector('span').textContent=duration(el.dataset.start,el.dataset.end||null));if(current)document.getElementById('modalTimer').textContent=duration(current.inicio,current.fim)};setInterval(updateTimer,1000);updateTimer();
 const showSection=async(name)=>{if(name==='despesas'&&canEdit&&!current.arquivada&&current.iniciada&&current.etapa<3){await request(current.viewExpensesUrl,{method:'POST'});current.etapa=3}document.querySelectorAll('.modal-section').forEach(x=>x.classList.toggle('active',x.id===`section-${name}`));document.querySelectorAll('.modal-nav').forEach(x=>x.classList.toggle('active',x.dataset.section===name));const unlocked=current.etapa>=3||current.arquivada;document.getElementById('navConclusao').disabled=!unlocked;document.getElementById('conclusaoBloqueada').classList.toggle('d-none',unlocked);document.getElementById('conclusaoForm')?.classList.toggle('d-none',!unlocked||current.arquivada)};
 const openModal=id=>{current=items[id];if(!current||!canView)return;feedback('');document.getElementById('modalEquipamento').textContent=current.equipamento;document.getElementById('modalLocal').textContent=current.local;document.getElementById('modalAgendamento').textContent=current.agendamento;document.getElementById('modalPrazo').textContent=current.prazo;document.getElementById('modalStatus').textContent=current.status;document.getElementById('modalTecnico').textContent=current.tecnico;document.getElementById('modalSituacao').textContent=current.situacao||'—';document.getElementById('readonlyNote').classList.toggle('d-none',canEdit&&!current.arquivada);document.getElementById('despesaForm')?.classList.toggle('d-none',current.arquivada);document.getElementById('conclusaoLeitura').classList.toggle('d-none',!current.arquivada);document.getElementById('conclusaoSituacao').textContent=current.situacao||'Situação não informada';document.getElementById('conclusaoObservacao').textContent=current.observacao||'Sem observações.';if(produto){$(produto).val('').trigger('change');quantidade.value='';updateProduct()}renderExpenses();showSection('resumo');updateTimer();modal.show()};
 document.querySelectorAll('.manutencao-card').forEach(card=>{const activate=async()=>{if(!canView)return;const item=items[card.dataset.id];if(!item.iniciada&&!item.arquivada&&canEdit){if(!confirm('Deseja iniciar esta manutenção agora? O tempo começará a contar imediatamente.'))return;try{const json=await request(item.startUrl,{method:'POST',body:new URLSearchParams({filtro})});location.href=json.redirect}catch(e){alert(e.message)}return}openModal(card.dataset.id)};card.addEventListener('click',e=>{if(e.target.closest('.pecas-toggle,.pecas-lista'))return;activate()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});
 document.querySelectorAll('.pecas-toggle').forEach(button=>button.addEventListener('click',()=>{const list=button.nextElementSibling;list.classList.toggle('d-none');button.setAttribute('aria-expanded',String(!list.classList.contains('d-none')))}));
 document.querySelectorAll('.modal-nav').forEach(button=>button.addEventListener('click',()=>showSection(button.dataset.section).catch(e=>feedback(e.message,'danger'))));
 document.getElementById('despesaForm')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');button.disabled=true;try{const json=await request(current.expenseUrl,{method:'POST',body:new FormData(e.target)});current.despesas.unshift(json.despesa);current.total=json.total;updateStock(json.compra_id,json.estoque);quantidade.value='';calculateCost();renderExpenses();feedback(json.message)}catch(error){feedback(error.message,'danger')}finally{button.disabled=false}});
 document.getElementById('despesasLista').addEventListener('click',async e=>{const button=e.target.closest('.remove-expense');if(!button||!confirm('Excluir esta despesa e devolver a quantidade ao estoque?'))return;button.disabled=true;try{const json=await request(`${current.expenseUrl}/${button.dataset.id}`,{method:'DELETE'});current.despesas=current.despesas.filter(d=>Number(d.id)!==Number(button.dataset.id));current.total=json.total;updateStock(json.compra_id,json.estoque);renderExpenses();feedback(json.message)}catch(error){button.disabled=false;feedback(error.message,'danger')}});
 document.getElementById('conclusaoForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Concluir e arquivar esta manutenção?'))return;try{const body=new FormData(e.target);body.append('filtro',filtro);const json=await request(current.finishUrl,{method:'POST',body});location.href=json.redirect}catch(error){feedback(error.message,'danger')}});
 const autoOpen=@json($abrirId);if(autoOpen&&items[autoOpen]&&canView)openModal(autoOpen);
});
</script>
@endpush
