@extends('layouts.app')
@section('title','Compras')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
<div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3 mb-4"><div><h1 class="page-title">Cadastro de compras</h1><p class="page-description mb-0">Consulte e gerencie os itens comprados.</p></div><div class="d-flex gap-2"><a href="{{ url('/') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Voltar</a>@if($giPermissoes->permite('compras.criar'))<a href="{{ route('compras.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Adicionar compra</a>@endif</div></div>
@if(session('status'))<div class="alert alert-success alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div class="card content-card"><div class="card-header d-flex justify-content-between align-items-center gap-3"><h5>Compras cadastradas</h5><div class="form-check form-switch mb-0"><input id="visualizarApagados" class="form-check-input" type="checkbox" @checked($includeDeleted)><label for="visualizarApagados" class="form-check-label">Visualizar apagadas</label></div></div><div class="card-body p-0"><div class="table-responsive"><table id="comprasTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Título</th><th>Unidade</th><th>Quantidade de pacotes</th><th>Qtd. unitária no pacote</th><th>Qtd. utilizada</th><th>Preço pacote</th><th>Preço unit.</th><th>Comprador</th><th>Data da compra</th><th>Status</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></div></div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{new DataTable('#comprasTable',{processing:true,serverSide:true,ajax:@json(route('compras.data',['include_deleted'=>$includeDeleted?1:null],false)),order:[[0,'desc']],columns:[{data:'id'},{data:'titulo'},{data:'unidade'},{data:'quantidade'},{data:'quantidade_unitaria'},{data:'qtde_utilizada'},{data:'preco'},{data:'preco_unitario',orderable:false},{data:'comprador'},{data:'data_compra'},{data:'status',searchable:false},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',search:'Pesquisar:',lengthMenu:'Exibir _MENU_ registros',info:'Exibindo _START_ a _END_ de _TOTAL_ compras',infoEmpty:'Nenhuma compra encontrada',emptyTable:'Nenhuma compra cadastrada',zeroRecords:'Nenhum registro encontrado',paginate:{first:'Primeira',last:'Última',next:'Próxima',previous:'Anterior'}}});document.addEventListener('submit',e=>{let m=null;if(e.target.matches('.excluir-compra-form'))m='Deseja mover esta compra para os registros apagados?';if(e.target.matches('.restaurar-compra-form'))m='Deseja restaurar esta compra?';if(e.target.matches('.apagar-compra-form'))m='ATENÇÃO: deseja excluir esta compra permanentemente?';if(m&&!confirm(m))e.preventDefault()});document.getElementById('visualizarApagados').onchange=function(){const u=new URL(location.href);this.checked?u.searchParams.set('include_deleted','1'):u.searchParams.delete('include_deleted');location.href=u}});</script>@endpush
