@extends('layouts.app')
@section('title','Checklist Concluído')
@push('styles')<style>.room-grid{display:flex;flex-wrap:wrap;gap:.75rem}.room-button{width:52px;height:52px;border:0;border-radius:50%;display:grid;place-items:center;font-weight:700}.room-complete{background:var(--bs-success);color:#fff}.room-warning{background:var(--bs-warning);color:#332701}.room-danger{background:var(--bs-danger);color:#fff}.equipment-row{border-bottom:1px solid var(--bs-border-color);padding:1rem 0}.equipment-row:last-child{border-bottom:0}</style>@endpush
@section('content')
@php $turnos=['m'=>'Manhã','t'=>'Tarde','n'=>'Noite']; @endphp
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h1 class="page-title">Checklist Concluído #{{ $checklist->id }}</h1><p class="page-description mb-0">Visualização somente leitura.</p></div><a href="{{ route('checklist_terminados.index') }}" class="btn btn-outline-secondary align-self-start"><i class="bi bi-arrow-left me-1"></i>Voltar</a></div><div class="card content-card mb-4"><div class="card-header"><h5>Dados da verificação</h5></div><div class="card-body p-4"><div class="row g-3">@foreach([['Clínica',$checklist->clinica?->titulo],['Responsável',$checklist->pessoaResponsavel?->nome],['Turno',$turnos[$checklist->turno]??'—'],['Início',$checklist->inicio?->format('d/m/Y H:i:s')],['Fim',$checklist->fim?->format('d/m/Y H:i:s')],['Duração',$checklist->inicio&&$checklist->fim?$checklist->inicio->diff($checklist->fim)->format('%H:%I:%S'):null]] as [$label,$value])<div class="col-md-4"><div class="form-label">{{ $label }}</div><div class="form-control bg-body-tertiary">{{ $value?:'—' }}</div></div>@endforeach</div></div></div><div class="card content-card"><div class="card-header"><h5>Consultórios verificados</h5></div><div class="card-body p-4"><div class="room-grid">@for($room=1;$room<=(int)$checklist->clinica?->consultorios;$room++)<button type="button" class="room-button room-{{ $statusConsultorios[$room] ?? 'complete' }}" data-room="{{ $room }}">{{ $room }}</button>@endfor</div></div></div>
<div class="modal fade" id="readonlyModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 id="readonlyTitle" class="modal-title"></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div id="readonlyList" class="modal-body"></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button></div></div></div></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const equipamentos=@json($equipamentos->map(fn($e)=>['id'=>$e->id,'titulo'=>$e->titulo])->values()),items=@json($itens),modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('readonlyModal')),key=(room,id)=>`${room}-${id}`,escapeHtml=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));document.querySelectorAll('.room-button').forEach(button=>button.addEventListener('click',()=>{const room=Number(button.dataset.room);document.getElementById('readonlyTitle').textContent=`Consultório ${room}`;document.getElementById('readonlyList').innerHTML=equipamentos.map(e=>{const item=items[key(room,e.id)],problem=item?.problema,state=item?.estado,label=state===1?'OK':(state===2?'Problema resolvido':'Problema não resolvido'),badge=state===1?'text-bg-success':(state===2?'text-bg-warning':'text-bg-danger');return `<div class="equipment-row"><div class="d-flex justify-content-between"><strong>${escapeHtml(e.titulo)}</strong><span class="badge ${badge}">${label}</span></div>${problem?`<div class="alert ${state===0?'alert-danger':'alert-warning'} mt-2 mb-0">${escapeHtml(problem)}</div>`:''}</div>`}).join('');modal.show()}))});</script>@endpush
