@extends('layouts.app')
@section('title','Checklist de Verificação')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">
<style>.room-grid{display:flex;flex-wrap:wrap;gap:.75rem}.room-button{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;font-weight:700;border:2px solid transparent;transition:.2s}.room-empty{background:#e9ecef;color:#6c757d}.room-partial{background:var(--bs-info);color:#052c65}.room-complete{background:var(--bs-success);color:#fff}.room-warning{background:var(--bs-warning);color:#332701}.room-button:hover{transform:translateY(-2px);box-shadow:0 .3rem .7rem rgba(0,0,0,.15)}.check-state{min-width:122px}.equipment-row{border-bottom:1px solid var(--bs-border-color);padding:1rem 0}.equipment-row:last-child{border-bottom:0}.timer{font-variant-numeric:tabular-nums;font-size:1.8rem;font-weight:700;letter-spacing:.06em}</style>
@endpush
@section('content')
@php
	$turnos=['m'=>'Manhã','t'=>'Tarde','n'=>'Noite'];
	$checklistItemUrl=$checklist?route('checklist.item',$checklist,false):null;
	$minutesNow=(int) now()->format('H') * 60 + (int) now()->format('i');
	$turnoSugerido=$minutesNow >= 360 && $minutesNow <= 720 ? 'm' : ($minutesNow >= 721 && $minutesNow < 1080 ? 't' : 'n');
@endphp
<div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h1 class="page-title">Checklist de Verificação</h1><p class="page-description mb-0">Verificação dos equipamentos por consultório.</p></div><a href="{{ route('checklist_terminados.index') }}" class="btn btn-outline-primary align-self-start"><i class="bi bi-clock-history me-1"></i>Checklists concluídos</a></div>
@if(session('status'))<div class="alert alert-success alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div id="checklistFeedback"></div>
@if($errors->any())<div class="alert alert-danger"><strong>Verifique os campos informados.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card content-card mb-4"><div class="card-header"><h5>Dados da verificação</h5></div><div class="card-body p-4">
@if(!$checklist)<form method="POST" action="{{ route('checklist.start') }}">@csrf<div class="row g-3 align-items-end"><div class="col-lg-4"><label for="ambiente_id" class="form-label">Clínica</label><select id="ambiente_id" name="ambiente_id" class="form-select" required><option value="">Selecione uma clínica</option>@foreach($clinicas as $clinica)<option value="{{ $clinica->id }}">{{ $clinica->titulo }} ({{ $clinica->consultorios }} consultórios)</option>@endforeach</select></div><div class="col-md-6 col-lg-3"><label class="form-label">Data e hora de início</label><input type="datetime-local" class="form-control" value="{{ now()->format('Y-m-d\TH:i') }}" disabled></div><div class="col-md-6 col-lg-3"><label class="form-label">Responsável</label><input class="form-control" value="{{ $responsavel }}" disabled></div><div class="col-lg-2"><label for="turno" class="form-label">Turno</label><select id="turno" name="turno" class="form-select" required>@foreach($turnos as $value=>$label)<option value="{{ $value }}" @selected(old('turno', $turnoSugerido) === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-primary btn-lg w-100 py-3"><i class="bi bi-play-circle-fill me-2"></i>Iniciar verificação</button></div></div></form>
@else<div class="row g-3 align-items-center"><div class="col-md-4"><div class="form-label">Clínica</div><div class="form-control bg-body-tertiary">{{ $checklist->clinica?->titulo }} ({{ $checklist->clinica?->consultorios }} consultórios)</div></div><div class="col-md-3"><div class="form-label">Responsável</div><div class="form-control bg-body-tertiary">{{ $responsavel }}</div></div><div class="col-md-2"><div class="form-label">Turno</div><div class="form-control bg-body-tertiary">{{ $turnos[$checklist->turno]??'—' }}</div></div><div class="col-md-3 text-center"><div class="form-label">Tempo decorrido</div><div id="cronometro" class="timer text-primary" data-inicio="{{ $checklist->inicio?->toIso8601String() }}">00:00:00</div></div><div class="col-12"><button id="finalizarChecklist" class="btn btn-success btn-lg w-100 py-3" data-url="{{ route('checklist.finish',$checklist) }}"><i class="bi bi-check-circle-fill me-2"></i>Finalizar verificação</button></div></div>@endif
</div></div>
@if($checklist)
<div class="card content-card"><div class="card-header d-flex justify-content-between align-items-center"><h5>Consultórios</h5><div class="d-flex flex-wrap gap-2 small"><span class="badge text-bg-secondary">Não iniciado</span><span class="badge text-bg-info">Em andamento</span><span class="badge text-bg-success">Tudo OK</span><span class="badge text-bg-warning">Com problema</span></div></div><div class="card-body p-4"><div id="roomGrid" class="room-grid">@for($room=1;$room<=(int)$checklist->clinica?->consultorios;$room++)<button type="button" class="room-button room-empty" data-room="{{ $room }}" title="Consultório {{ $room }}">{{ $room }}</button>@endfor</div></div></div>
<div class="modal fade" id="roomModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 id="roomTitle" class="modal-title">Consultório</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div id="equipmentList" class="modal-body"></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button></div></div></div></div>
@endif
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{$('#ambiente_id').select2({theme:'bootstrap-5',width:'100%',placeholder:'Selecione uma clínica'});
@if($checklist)
const csrf=@json(csrf_token()),itemUrl=@json($checklistItemUrl),equipamentos=@json($equipamentos->map(fn($e)=>['id'=>$e->id,'titulo'=>$e->titulo])->values()),items=@json($itens),feedback=document.getElementById('checklistFeedback'),modal=bootstrap.Modal.getOrCreateInstance(document.getElementById('roomModal'));let currentRoom=null;const escapeHtml=value=>String(value??'').replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char])),stateClass={empty:'room-empty',partial:'room-partial',complete:'room-complete',warning:'room-warning'},showMessage=(text,type='warning')=>feedback.innerHTML=`<div class="alert alert-${type} alert-dismissible fade show">${escapeHtml(text)}<button class="btn-close" data-bs-dismiss="alert"></button></div>`,key=(room,equipment)=>`${room}-${equipment}`,roomStatus=room=>{const values=equipamentos.map(e=>items[key(room,e.id)]).filter(Boolean);return values.length===0?'empty':values.length<equipamentos.length?'partial':values.some(i=>i.estado===0)?'warning':'complete'},paintRooms=()=>document.querySelectorAll('.room-button').forEach(button=>{const status=roomStatus(Number(button.dataset.room));button.className=`room-button ${stateClass[status]}`});
const stateButton=item=>item?.estado===1?'<span class="btn btn-success check-state"><i class="bi bi-check-circle-fill me-1"></i>OK</span>':item?.estado===0?'<span class="btn btn-warning check-state"><i class="bi bi-exclamation-triangle-fill me-1"></i>Problema</span>':'<span class="btn btn-outline-secondary check-state"><i class="bi bi-dash-circle me-1"></i>Não verificado</span>';
const renderRoom=room=>{currentRoom=room;document.getElementById('roomTitle').textContent=`Consultório ${room}`;document.getElementById('equipmentList').innerHTML=equipamentos.map(e=>{const item=items[key(room,e.id)],problem=item?.problema||'';return `<div class="equipment-row" data-equipment="${e.id}"><div class="d-flex justify-content-between align-items-center gap-3"><strong>${escapeHtml(e.titulo)}</strong><div class="d-flex gap-2"><button type="button" class="border-0 bg-transparent p-0 state-toggle">${stateButton(item)}</button>${item?.estado===0?'<button type="button" class="btn btn-outline-warning problem-toggle" title="Mostrar ou ocultar problema"><i class="bi bi-chat-left-text"></i></button>':''}</div></div><div class="problem-area ${item?.estado===0?'':'d-none'} mt-3"><textarea maxlength="50" rows="2" class="form-control problem-text" placeholder="Descreva o problema (máximo 50 caracteres)">${escapeHtml(problem)}</textarea></div></div>`}).join('');modal.show()};
const save=async(row,state,problem='')=>{const response=await fetch(itemUrl,{method:'PUT',headers:{'Content-Type':'application/json',Accept:'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({consultorio:currentRoom,equipamento_id:Number(row.dataset.equipment),estado:state,problema:problem})});const body=await response.json();if(!response.ok)throw new Error(body.message||'Não foi possível salvar.');Object.keys(items).forEach(k=>delete items[k]);Object.assign(items,body.itens);paintRooms();renderRoom(currentRoom);if(state===1&&roomStatus(currentRoom)==='complete')modal.hide()};
document.getElementById('roomGrid').addEventListener('click',event=>{const button=event.target.closest('.room-button');if(button)renderRoom(Number(button.dataset.room))});document.getElementById('equipmentList').addEventListener('click',event=>{const row=event.target.closest('.equipment-row');if(!row)return;if(event.target.closest('.problem-toggle')){row.querySelector('.problem-area').classList.toggle('d-none');return}if(event.target.closest('.state-toggle')){const item=items[key(currentRoom,Number(row.dataset.equipment))],next=!item?1:item.estado===1?0:null;save(row,next,next===0?(item?.problema||''):'').catch(error=>showMessage(error.message,'danger'))}});document.getElementById('equipmentList').addEventListener('change',event=>{if(!event.target.matches('.problem-text'))return;const row=event.target.closest('.equipment-row');save(row,0,event.target.value).then(()=>{if(roomStatus(currentRoom)!=='partial')modal.hide()}).catch(error=>showMessage(error.message,'danger'))});
const started=new Date(document.getElementById('cronometro').dataset.inicio).getTime(),timer=()=>{const seconds=Math.max(0,Math.floor((Date.now()-started)/1000)),h=String(Math.floor(seconds/3600)).padStart(2,'0'),m=String(Math.floor(seconds%3600/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.getElementById('cronometro').textContent=`${h}:${m}:${s}`};timer();setInterval(timer,1000);paintRooms();document.getElementById('finalizarChecklist').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{const response=await fetch(button.dataset.url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf}}),body=await response.json();if(!response.ok){showMessage(body.message);if(body.next){renderRoom(body.next.consultorio);setTimeout(()=>document.querySelector(`[data-equipment="${body.next.equipamento_id}"] .state-toggle`)?.focus(),300)}return}location.href=body.redirect}catch(error){showMessage(error.message,'danger')}finally{button.disabled=false}});
@endif});</script>
@endpush
