@extends('layouts.app')
@section('title','Manutenções Corretivas')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
@php($corretivasDataUrl=route('corretiva.data', [], false))
<div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3 mb-4"><div><h1 class="page-title">Lançamento de Manutenções Corretivas</h1><p class="page-description mb-0">Consulte e registre as manutenções corretivas dos equipamentos.</p></div><div class="d-flex gap-2"><a href="{{ url('/') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Voltar</a>@if($giPermissoes->permite('corretiva.criar'))<a href="{{ route('corretiva.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Adicionar lançamento</a>@endif</div></div>
@if(session('status'))<div class="alert alert-success alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div class="card content-card"><div class="card-header"><h5>Manutenções corretivas</h5></div><div class="card-body p-0"><div class="table-responsive"><table id="corretivasTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Ativo / Equipamento</th><th>Local - Unidade</th><th>Solicitante</th><th>Data da manutenção</th><th>Status da manutenção</th><th>Ativação</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></div></div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{new DataTable('#corretivasTable',{processing:true,serverSide:true,ajax:@json($corretivasDataUrl),order:[[0,'desc']],columns:[{data:'id'},{data:'equipamento'},{data:'local'},{data:'solicitante'},{data:'data_manutencao'},{data:'descricao'},{data:'status',searchable:false},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',search:'Pesquisar:',lengthMenu:'Exibir _MENU_ registros',info:'Exibindo _START_ a _END_ de _TOTAL_ lançamentos',infoEmpty:'Nenhum lançamento encontrado',emptyTable:'Nenhuma manutenção corretiva cadastrada',zeroRecords:'Nenhum registro encontrado',paginate:{first:'Primeira',last:'Última',next:'Próxima',previous:'Anterior'}}});document.addEventListener('submit',event=>{if(event.target.matches('.excluir-corretiva-form')&&!confirm('Deseja excluir esta manutenção corretiva?'))event.preventDefault()})});</script>@endpush
