@extends('layouts.app')
@section('title','Clínicas')
@push('styles')<link href="https://cdn.datatables.net/2.3.2/css/dataTables.bootstrap5.min.css" rel="stylesheet">@endpush
@section('content')
@php($clinicasDataUrl=route('clinicas.data', ['include_deleted'=>$includeDeleted?1:null], false))
<div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3 mb-4"><div><h1 class="page-title">Clínicas</h1><p class="page-description mb-0">Consulte e gerencie as clínicas e seus consultórios.</p></div><div class="d-flex gap-2"><a href="{{ url('/') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Voltar</a>@if($giPermissoes->permite('clinica.criar'))<a href="{{ route('clinicas.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Adicionar clínica</a>@endif</div></div>
@if(session('status'))<div class="alert alert-success alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
<div class="card content-card"><div class="card-header d-flex justify-content-between align-items-center gap-3"><h5>Clínicas cadastradas</h5><div class="form-check form-switch mb-0"><input id="visualizarApagadas" class="form-check-input" type="checkbox" @checked($includeDeleted)><label for="visualizarApagadas" class="form-check-label">Visualizar apagadas</label></div></div><div class="card-body p-0"><div class="table-responsive"><table id="clinicasTable" class="table table-hover align-middle w-100 mb-0"><thead><tr><th>ID</th><th>Título</th><th>Consultórios</th><th>Status</th><th>Criado em</th><th>Alterado em</th><th>Apagado em</th><th data-dt-order="disable">Ações</th></tr></thead><tbody></tbody></table></div></div></div>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.min.js"></script><script src="https://cdn.datatables.net/2.3.2/js/dataTables.bootstrap5.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{new DataTable('#clinicasTable',{processing:true,serverSide:true,ajax:@json($clinicasDataUrl),order:[[0,'desc']],columns:[{data:'id'},{data:'titulo'},{data:'consultorios'},{data:'status',searchable:false},{data:'criado_em'},{data:'alterado_em'},{data:'apagado_em'},{data:'acoes',orderable:false,searchable:false}],language:{processing:'Carregando...',search:'Pesquisar:',lengthMenu:'Exibir _MENU_ registros',info:'Exibindo _START_ a _END_ de _TOTAL_ clínicas',infoEmpty:'Nenhuma clínica encontrada',emptyTable:'Nenhuma clínica cadastrada',zeroRecords:'Nenhum registro encontrado',paginate:{first:'Primeira',last:'Última',next:'Próxima',previous:'Anterior'}}});document.addEventListener('submit',event=>{let text=null;if(event.target.matches('.excluir-clinica-form'))text='Deseja mover esta clínica para os registros apagados?';if(event.target.matches('.restaurar-clinica-form'))text='Deseja restaurar esta clínica?';if(event.target.matches('.apagar-clinica-form'))text='Deseja excluir esta clínica permanentemente?';if(text&&!confirm(text))event.preventDefault()});document.getElementById('visualizarApagadas').onchange=function(){const url=new URL(location.href);this.checked?url.searchParams.set('include_deleted','1'):url.searchParams.delete('include_deleted');location.href=url}});</script>@endpush
